[package]
name = "datbase_handler"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.1"
egui = "0.32.1"
egui_extras = "0.32.1"
env_logger = "0.11.8"
log = "0.4.27"
rusqlite = "0.37.0"
text_io = "0.1.13"
